jobs:
  test_my_api:
    executor: sam/default
    steps:
      - run: echo "Run your tests here"
orbs:
  sam: circleci/aws-sam-serverless@x.y.z
version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-staging
          stack-name: staging-stack
          template: ./node.yml
      - test_my_api:
          requires:
            - deploy-staging
      - sam/deploy:
          name: deploy-production
          requires:
            - test_my_api
          stack-name: production-stack
          template: ./node.yml


