jobs:
  build_app:
    executor: aws-serverless/default
    steps:
      - checkout
      - sam/install
      - run: sam build
  test_my_api:
    executor: sam/default
    steps:
      - run: echo "Run your tests here"
orbs:
  sam: circleci/aws-sam-serverless@1.0.1
version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - build_app
      - sam/deploy:
          name: deploy-staging
          stack-name: staging-stack
          s3-bucket: lambda-skeleton-bucket
          template: .circleci/node.yml
      - test_my_api:
          requires:
            - deploy-staging
      - sam/deploy:
          name: deploy-production
          requires:
            - test_my_api
          stack-name: production-stack
          s3-bucket: lambda-skeleton-bucket
          template: .circleci/node.yml


